### ISSUE TITLE
Update pfile format

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/xania#28]
Maybe something like YAML?

We should tests we can losslessly roundtrip the new format and compare it back with the original old format.

**Comment by snellers** [comment]
This would be the basis for some "extended" content in pfiles for some new features....

**Comment by mattgodbolt** [comment]
YAML seems a good fit. Just tried hand-converting a bit of a mismash of my own pfile and a basic one:
```yaml
---
Name: TheMoog
Version: 3
Character:
  Race: human
  Sex: Male
  Class: Mage
  Level: 2
  Played: 9028
  Room: 3712
  Attributes:
    Base:
      Int: 14
      # etc
    Modifiers:
      Int: 0
  HealthManaMove:
    Base: [25, 25, 106, 106, 106, 106]
    Permanent: [25, 106, 106]
  Gold: 43
Options:
  Note: 0
  Scroll: 22
  Wimpy: 4
  Password: BLAHBLAH
  Title: " the Apprentice of Magic"
  Afk: ""
  Colour: True
  Info:
    Name: ""
    Email: ""
    LastLoginFrom: ""
    LastLoginAt: ""
    # extra bits can probably die. it's part of Info
    ExtraBits: 00000000000000000000000000
  Prefix: ""
  HourOffset: 0
  MinOffset: 0
Condition: [0, 0, 0]
Skills:
  "acid blast": 1
  "Octarine fire": 1
    # etcetc
  "magic missile": 75
  recall: 50
Groups:
  - rom basics
  - combat
  - etc
Affects:
  - type: armor
    # things here
Inventory:
  - Vnum: 3703 # a sub issue vest
    Wear: body
  - Vnum: 3705 # a sub issue blah
  - Vnum: 23 # a hand-written scroll of %s
    Name: scroll hand written handwritten charm person
    ShortDescription: a hand-written scroll of charm person
    Description: A hand-written scroll of charm person lies here.
    Level: 100
    Val: 100 15 -1 -1 -1
    Spell: 1 'charm person'
```

things like containers fall out naturally, and we can use comments to make them somewhat human-parseable.
